### PR TITLE
WIP: technic_HSTL_Server.json

### PR DESCRIPTION
**Pull request by QORTEC**
I was just updating my packs information and noticed that there is a new system;

I wrote a script that quickly created the mod listing, the json file should be correctly formatted.
It's probable that the list contains mods that don't really add any textures, I will go through the list thoroughly and remove any unneeded entries (when I have some more time).

If it makes it easier; feel free to hold back this pull request until its cleaned up.

### CODE REVIEW

**Comment by artdude543** [comment]
Can you update this PR with the spaces change to 2 spaces instead of tabs please?

**Comment by QORTEC** [comment]
Sorry it took so long to fix it up, it should ready to be pulled.

How often are the texture packs build with your auto build system?

**Comment by QORTEC** [comment]
I updated the Texture Pack, @artdude543 is there anything else I should to do before it gets pulled?

**Comment by artdude543** [comment]
Hey sorry with slow progress on this, been busy with Minecon preparations and such. But I'll merge this now, once deployed downloads will be updated on a 24 hour basis. And your URL should stay the same but will find out after the script has ran again.

**Comment by QORTEC** [comment]
Thank you, I hope you will have a successful Minecon.

**Pull request merged**
