### PR TITLE
Initial submission for Beyond Reality Mod Pack

### PR DESCRIPTION
**Pull request by leagris**
### Website URI:
http://beyondrealitypack.com/

### Repository:
https://github.com/Beyond-Reality/BeyondRealityModPack

### Modpack maintainers:
@Buuz135
@Dyonovan

### Soartex for Beyond Reality:
@leagris

Please check and ease Beyond Reality players, into the best possible Soartex experience, by enabling this resource packaging into Soartex CDNs.

Reference doc:
http://wiki.soartex.net/modded/02-04-2015/making-a-modpack-json/

### CODE REVIEW

**Comment by artdude543** [comment]
Thanks for making the fixes ^_^

**Comment by artdude543** [comment]
I'll get the dev script ran in a hour or so and report back with the fail / success on the build. (I may end up creating a Jenkins script or something to test the files before being pushed to the main server)

**Comment by leagris** [comment]
@artdude543 Did you had issues with the parameters in the pack?

**Comment by artdude543** [comment]
Yup sorry, just ran it now and it was fine :) Should show on the site in the next few days we are nearly done for the major site update. /me crosses fingers

**Comment by leagris** [comment]
Le 13/06/2015 22:55, Kieron Richardson a écrit :
> Yup sorry, just ran it now and it was fine :) Should show on the site in
> the next few days we are nearly done for the major site update. /me
> crosses fingers

Any chance you can already give the CDN URI so we can add the option to
ATLauncher?

Thanks,

-- 
Léa Gris

**Comment by artdude543** [comment]
Screenshoot of it sitting on the dev site :P 
screenshot 2015-06-13 21 57 26

Umm, give me a min and I'll generate the link for ya.

**Comment by artdude543** [comment]
Sorry for the delay, decided to update all the downloads at the same time. But here is your link: http://soartex.cursecdn.com/fanver/modded/1.7.x/modpacks/atlauncher/Fanver_Beyond_Reality.zip

**Comment by leagris** [comment]
Thank you very much @@artdude543

We did test the resource and it is working fine except for one thing:

GregTech assets are very outdated compared to current GitHub:
https://gist.github.com/leagris/f8a557484cf6bd375f21

Machines icon overlays and GUIs are missing. It means this is like 6
months old.

There are probably other mods assets that would really need a resynk
from Git.
I hope you can come-up with updating the CDN resources soon and have
more frequent routine updates :)

Regards,

**Comment by artdude543** [comment]
The script pulls from GitHub each time so its not the CDN's end. I guess mod-id's are not synced on the repo here. As we have two GregTech folders so I guess its that causing the issue.

**Comment by artdude543** [comment]
Yeah both folders are using the same `modid` If we are keeping both I'd recommend the `v6` being prefixed with `_v6` on the end of the `mod.json` file.

**Comment by leagris** [comment]
Fixed in: Soartex-Modded/Modded-1.7.x@c98a166

**Comment by artdude543** [comment]
Awesome, you going to update your pack json or want me too? I'll re-run the script in a bit after the edit is made.

**Comment by leagris** [comment]
No need to update my pack json,
It needs the standard older gregtech5 with unchanged mod_id

**Comment by artdude543** [comment]
Ahh okies, will let you know when I get the script ran again. ^_^

**Comment by leagris** [comment]
> Ahh okies, will let you know when I get the script ran again. ^_^
Any chance you can re-run this script soon @artdude543 :grey_question:
:eyes:

**Pull request merged**
