### PR TITLE
TDV2016 modpack 

### PR DESCRIPTION
**Pull request by TDVagabond**
Mods in TDV2016 modpack that have textures

### CODE REVIEW

**Comment by artdude543** [comment]
This is not using the correct format.

The file should be a `json` file not a Word Document. Along with it needs to be in the `packs/` folder and not a custom one as our backend won't care for the new folder. Please update to that format and remove the `txt` file as that's not needed. You can comment that on here instead if you want to talk about that. But in regards to changing textures this is something we cannot provide. You'd need to create the textures yourself and publish them for our server to use.

**Comment by TDVagabond** [comment]
In txt was that:
1) would like to villagers have skin of racoon as maskot of Beam is racoon
2) in pictures and profile picture of Aknotsdeath's and Chickari2010's on Beam as they helped me
If you don't want to do it, I would do it if that's OK.

**Comment by Darkosto** [comment]
He read your message in the original file. That's not where the discrepancy is. Since you're asking for images/assets that are not already part of Soartex YOU will need to create them yourself and have them approved. Also, I strongly suggest spell checking your messages from now on, especially when you misspell "json". Spelling and correct file formatting are extremely important when working with scripting/code.

**Comment by TDVagabond** [comment]
Understand, will do it correctly in future. But, is it all good? Will it be
made?

**Comment by Darkosto** [comment]
Not to be rude, but did you actually read the responses?

**Comment by artdude543** [comment]
I have said in my first comment on what needs to be changed. I can point you back to [here](http://wiki.soartex.net/modded/02-04-2015/making-a-modpack-json/) which fully explains how to create the files. Then you only need to put the file in the `packs/` directory.

**Comment by TDVagabond** [comment]
I did put it in packs/ directory...

On Tue, Aug 16, 2016 at 6:09 PM, Kieron Richardson <notifications@github.com

**Comment by TDVagabond** [comment]
And did make json file (tdv2016.json)

**Comment by artdude543** [comment]
In the PR you sent to the repo it did not contain the JSON file but a word doc file which has JSON data in it. That is not a valid JSON file which is what this repo needs. All you'd need to do is move the data to a file called `mypack.json` which is a JSON file not a doc file.

**Pull request closed without merging**
